### ISSUE TITLE
如何配置404页面

### ISSUE THREAD

**Issue by admin8756** [ArcherGu/vite-static-site#2]
按照教程。我成功的运行了js版本的vite - ssg 。但是。我发现这个项目缺少一个非常关键的东西。404页面。应该如何配置呢

**Comment by ArcherGu** [comment]
抱歉，这个是我疏忽了，感谢提出来。现在我已经加上去了。

这个模板的路由是基于 [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) 插件的，它的文档里有写:
[vite-plugin-pages: Catch-all Routes](https://github.com/hannoeru/vite-plugin-pages#catch-all-routes)

具体的做法就是你可以通过创建一个`[...all].vue`文件来作为路由没法匹配的404页面。

**Comment by admin8756** [comment]
首先感谢您的解答。
其次和您说声，不好意思。因为我是个新手。我正在尝试学习Vue3。所以提出这个不太好的问题。
我觉得这个项目很棒。希望你继续加油。
另外我在`index.vue`的里面使用`<H1>`元素的时候。似乎会被那个识别组件然后添加到MD里的插件识别为VUE组件。
我会在晚上再次确认。如果可以复现，会再提一个新的Issues给您。
再次感谢您的解答。
