### ISSUE TITLE
部署至线上需要nginx支持吗，我打包放到线上后直接就走到了404页面

### ISSUE THREAD

**Issue by yanbowe** [ArcherGu/vite-static-site#3]
是在没有改任何代码的情况下

**Comment by ArcherGu** [comment]
正常来说是需要的，直接用nginx会作为后端路由使用，引导到目录对应的文件，但是这个项目中用的是history模式下的前端路由，所以你需要配置下nginx。[配置方法](https://next.router.vuejs.org/zh/guide/essentials/history-mode.html#nginx)

现在大多数前端项目都是SPA，路由也是前端控制，后端只是提供了一个像index.html这样的入口文件而已。

**Comment by yanbowe** [comment]
> 正常来说是需要的，直接用nginx会作为后端路由使用，引导到目录对应的文件，但是这个项目中用的是history模式下的前端路由，所以你需要配置下nginx。[配置方法](https://next.router.vuejs.org/zh/guide/essentials/history-mode.html#nginx)
> 
> 现在大多数前端项目都是SPA，路由也是前端控制，后端只是提供了一个像index.html这样的入口文件而已。

感谢
