### ISSUE TITLE
关于路由列表

### ISSUE THREAD

**Issue by admin8756** [ArcherGu/vite-static-site#4]
比如我写了很多篇文章。那么是不是需要维护一个静态的路由列表。然后实现跳转呢？
有没有办法可以根据文件的列表。输出一个菜单。进行维护呢

**Comment by ArcherGu** [comment]
是的，要维护一个路由列表，但是不用手动维护，可以通过router获取所有的路由，然后生成即可。
具体的操作方法可以看我的blog站代码：[archergu.me](https://github.com/ArcherGu/archergu.me)

**Comment by admin8756** [comment]
搜嘎。明白了~我也在思考这个。但是如果一个菜单是希望除了title。还有一个介绍的话。是不是就没有办法了。

**Comment by ArcherGu** [comment]
可以支持介绍啊。你仔细看我的文章，里面有写：
```
vite-plugin-pages 会自动把 pages 目录中的 .vue 和 .md 文件生成对应的路由，并且我们可以利用 markdown 的 front-matter 来为路由提供一些额外信息。
```
这些额外的信息会被放到route.meta下，这个就是vue-router的[路由元信息](https://next.router.vuejs.org/zh/guide/advanced/meta.html#%E8%B7%AF%E7%94%B1%E5%85%83%E4%BF%A1%E6%81%AF)。你可以利用这些路由元信息来做你的文章介绍，标签，或者其他东西

**Comment by admin8756** [comment]
搜嘎。明白了。谢谢
